### PR TITLE
Add basic documentation - how slashtags works

### PR DESCRIPTION
**Pull request by rolznz**
It would be great to have some simple doumentation on how slashtags works, with links on how to directly try it out without having to build it yourself. I don't understand how the full flow works but hope this is somewhat in the right direction.

### CODE REVIEW

**Comment by Nazeh** [comment]
Thanks @rolznz, I really appreciate the initiative, but it goes to show why I prefer building demos, especially ones that don't need to be built to be experienced (e.g slash-wallet.netlify.app).

What is described in this PR change, is the Authentication/Connection mechanism, as it currently stands. Which is both subject to change, but also is only a part of what Slashtags is set to be.

Slashtags is supposed to enable a decentralized WoT by having 2 main primitives in place:
1- Slashtags Identifiers (DID method, to control your identity and sign claims)
2- Personal Data storage (to save, and retrieve documents that make up this WoT)

Authentication is just one use case for decentralized identifiers, and should not be the focus. If anything is worth documenting it would be the general philosophy and goals, but I would rather put more demos in everyone's hands as often as possible.

**Comment by rolznz** [comment]
@Nazeh thanks for the additional information. It's great to see the power of what slashtags could do. The demo mostly works great, but this repository just feels a bit dead, without links and hard for people to see what the progress is and where things are going.

Maybe at least the demo links could be added to the main README or demo README so that people don't have to try build it (especially since the demos built from scratch might not work like they don't now).

**Comment by Nazeh** [comment]
It is pretty much not dead, but most of the work is on other branches than Master, but fair enough, I will feature the demos in the main README and maybe an up-to-date description of what we are currently working on/roadmap.

**Comment by rolznz** [comment]
Thanks, Nazeh!

**Pull request closed without merging**
