### PR TITLE
Fixed the demo app url

### PR DESCRIPTION
**Pull request by saubyk**
Hyperlinked the correct wallet demo url.
I am assuming it's https://slashtags.netlify.app, which I found on the Synonym website.

### CODE REVIEW

**Comment by Nazeh** [comment]
Thanks @saubyk, but that link is correct for the wallet demo. Is it not working for you?

**Comment by saubyk** [comment]
Hey @Nazeh I see that you closed the PR, but the link is still not working.

**Comment by Nazeh** [comment]
@saubyk that is weird, https://slash-wallet.netlify.app/ definitely is working for me. Anyway, as #34 branch is getting closer to merging, all README are going to be subject to lots of changes.

Let me know if the link is broken on your side, that would be worth investigating for later demos.

Thanks

**Comment by rbndg** [comment]
@saubyk what kind of network are you on? 
I've had the demo fail when using it at a hotel Wifi

**Comment by saubyk** [comment]
Hi @rbndg 
The link is failing for me all the time, because it's linked incorrectly I think. Please see below.

image

**Comment by gr0kchain** [comment]
can confirm @Nazeh . The link when clicking it from the github README render resolves to `https://github.com/synonymdev/slashtags/blob/master/slash-wallet.netlify.app` if you omit the `https://`

**Comment by Nazeh** [comment]
Thanks, @gr0kchain, and noted as I work on READMEs for #34

**Comment by Nazeh** [comment]
Documentation has been overhauled in the SDK branch that was just merged.
Closing this PR, but please feel free to point out any issuer with existing docs.

Thanks again @saubyk

**Pull request closed without merging**
